# Generated by Django 2.1.3 on 2019-05-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100, verbose_name='Char field')),
                ('checkbox_field', models.BooleanField(default=False, verbose_name='Checkbox field')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'inline entry',
                'verbose_name_plural': 'inline entries',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='InlineModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100, verbose_name='Char field')),
                ('checkbox_field', models.BooleanField(default=False, verbose_name='Checkbox field')),
                ('position', models.IntegerField(default=0, verbose_name='Position')),
            ],
            options={
                'verbose_name': 'inline entry 2',
                'verbose_name_plural': 'inline entries 2',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100, verbose_name='Char field')),
            ],
            options={
                'verbose_name': 'other entry',
                'verbose_name_plural': 'other entries',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(help_text='Help text', max_length=100, verbose_name='Char field')),
                ('choice_field', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'One'), (2, 'Two')], default=1, null=True, verbose_name='Choice field')),
                ('integer_field', models.IntegerField(blank=True, null=True, verbose_name='Integer field')),
                ('file_field', models.FileField(blank=True, upload_to='test_model', verbose_name='File field')),
                ('image_field', models.ImageField(blank=True, upload_to='test_model', verbose_name='Image field')),
                ('checkbox_field', models.BooleanField(default=False, help_text='Help text', verbose_name='Checkbox field')),
                ('fk_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_entries_fk', to='test_models.OtherModel', verbose_name='Fk field')),
            ],
            options={
                'verbose_name': 'test entry',
                'verbose_name_plural': 'test entries',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='inlinemodel2',
            name='fk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlines2', to='test_models.TestModel', verbose_name='TestModel'),
        ),
        migrations.AddField(
            model_name='inlinemodel2',
            name='other',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inlines2', to='test_models.OtherModel', verbose_name='OtherModel'),
        ),
        migrations.AddField(
            model_name='inlinemodel',
            name='fk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inlines', to='test_models.TestModel', verbose_name='TestModel'),
        ),
    ]
